-- Lexicon - PostgreSQL container initialization
--
-- PostgreSQL is optional and reserved for future use (no code reads or writes
-- it yet); its container starts only with `docker compose --profile postgres`.
--
-- The schema is managed by alembic only (migrations/). Create it with
--   make db-migrate                  # alembic upgrade head
-- and load the reference rows with
--   python scripts/load_initial_data.py
--
-- This script runs once, when the container initializes an empty data
-- directory. It is intentionally empty: put only server-level setup here
-- (extensions, roles), never tables, or alembic fails with
-- "relation ... already exists".
